Change bookmark button to always visible
sussy-code/smov pull request #82
Opened 2024-07-27 17:18 UTC by Pasithea0

Change bookmark button to always visible

 - [ x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [ x] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [ x] I have tested all of my changes.

2024-07-27 18:33 UTC, ztpn requested changes

2024-07-27 18:33 UTC, ztpn commented on src/components/media/MediaCard.tsx
> +          {true && (
Redundant conditional rendering?

2024-07-27 20:19 UTC, itzCozi commented
Lemme get a preview link

2024-08-06 17:39 UTC, Pasithea0 commented
https://bookmarks-always-visible.envyflix.pages.dev/
Bookmarks will always show for smaller screens, assuming they are on mobile and don't have a mouse to hover. Otherwise PR [44dddea](https://github.com/sussy-code/smov/pull/82/commits/44dddead7cabc2431566012308282b08a19f0d3e) is just always show, even on desktop.

2024-08-06 17:59 UTC, ztpn commented
we have an isMobile() somewhere

2024-08-06 18:00 UTC, ztpn commented
```typescript
import { useIsMobile } from "@/hooks/useIsMobile";
const { isMobile } = useIsMobile();
```

2024-08-20 05:12 UTC, merged