iOS PWA improvments
sussy-code/smov pull request #89
Opened 2024-08-15 20:46 UTC by Pasithea0

## This aims to solve most of the problems with the iOS PWA. 
Apple has restricted the use of many features for PWAs such as, not supporting Picture in Picture (PiP), breaking the functionality of the "standalone" display property, and always showing the home indicator on iPhone X and beyond.

Preview: https://pwa-improvements.envyflix.pages.dev/

## Changes:
### Disable PiP and Fullscreen for iOS PWA
- Disabled PiP and Fullscreen on iOS PWA only to mitigate Apple breaking the functionality, thus making the buttons useless.
### Add info button for iOS PWA
- Added a button in place of the Fullscreen button that shows an alert explaining why the PiP and Fullscreen buttons were removed.

<img width="400" alt="Screenshot 2024-08-15 at 2 29 31 PM" src="https://github.com/user-attachments/assets/108ded3e-d8e2-4542-ae67-ca1abe2010e7">
<img width="300" alt="Screenshot 2024-08-15 at 2 29 52 PM" src="https://github.com/user-attachments/assets/8840d9a6-fc19-4435-973c-8325d70d64aa">

### Add Widescreen button
- Due to the Fullscreen feature being disabled, the user can no longer fill their screen (remove letterboxing), so I reimplemented the feature back into the player.

<img width="500" alt="Screenshot 2024-08-15 at 2 31 44 PM" src="https://github.com/user-attachments/assets/b9c32cdf-ce82-46c3-9ad4-75b0b1f7cf4e">

https://github.com/user-attachments/assets/4fbffa82-22b2-4cca-9292-8b6a50e1b7d2

- I also made this a secret feature for desktop, only shown when holding the "SHIFT" key.

https://github.com/user-attachments/assets/e2ee6cf0-6bac-4cde-ba2b-d2ed0d3473f8

### Fix top padding and safe areas for iOS PWA
- The iOS PWA has an oversight that ignores the notch area, so I added safe areas for top elements.

BEFORE 
<img width="500" alt="Screenshot 2024-08-15 at 2 27 58 PM" src="https://github.com/user-attachments/assets/17bc5b7e-15ab-45a7-9643-d5cfe3391952">

AFTER
<img width="500" alt="Screenshot 2024-08-15 at 2 28 26 PM" src="https://github.com/user-attachments/assets/9f7bf349-bf10-4c2d-965b-707ef591b42b">

 - [x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.
 - Enter discord user: `.pasithea` (we require this for the contributor role)

2024-08-16 08:56 UTC, ztpn commented
Fucking apple

2024-08-27 05:04 UTC, Pasithea0 commented
Revert "Disable scrolling in player" due to disabling mobile pull to refresh feature. 
Good to merge.

2024-09-17 12:14 UTC, ztpn requested changes

2024-09-17 12:14 UTC, ztpn commented on src/pages/parts/player/PlayerPart.tsx
> +  const isIOSPWA =
Just make this a separate hook in /hooks

2024-09-17 12:14 UTC, ztpn commented on src/pages/parts/player/PlayerPart.tsx
> +  const [isShifting, setIsShifting] = useState(false);
this has to go since we aren't adding widescreen for now

2024-09-17 12:14 UTC, ztpn commented on src/pages/parts/player/PlayerPart.tsx
> +            {/* Fullscreen on when not shifting */}
Same here, all this has to go

2024-09-17 12:14 UTC, ztpn commented on src/pages/parts/player/PlayerPart.tsx
> +              <div>
You can just do 
```javascript
{!isIOSPWA && (<Player.Fullscreen />)}
```

2024-09-17 12:14 UTC, ztpn commented on src/pages/parts/player/PlayerPart.tsx
> +              <div>
same here

2024-12-20 15:09 UTC, closed without merging