new subtitle text colors
sussy-code/smov pull request #96
Opened 2024-09-07 17:44 UTC by Pasithea0

This pull request resolves #93 

Added black, red, and green

 - [x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.
 - Enter discord user: `.pasithea` (we require this for the contributor role)

2024-09-07 19:33 UTC, Saioni1 commented
Oh thanks man

2024-09-09 06:24 UTC, ztpn commented
Can we add an option for custom colors?

2024-09-09 06:24 UTC, Saioni1 commented
Yes, why not

2024-09-09 06:26 UTC, ztpn commented
> Yes, why not

WHO TF ASKED YOU

2024-09-09 06:26 UTC, Saioni1 commented
Oh

2024-09-09 06:27 UTC, Saioni1 commented
Then who did you ask?

2024-09-09 14:35 UTC, Pasithea0 commented
> Can we add an option for custom colors?

I can try, but the problem is that the css for the colors is generated when building. So it wouldn't be simple.

2024-09-10 05:35 UTC, Pasithea0 commented
> Can we add an option for custom colors?

Added 😘
https://envyflix-git-new-sub-colors-pasithea0s-projects.vercel.app/

2024-09-17 11:40 UTC, ztpn requested changes

2024-09-17 11:40 UTC, ztpn commented on src/components/player/atoms/settings/CaptionSettingsView.tsx
> +export const colors = ["#ffffff", "#80b1fa", "#e2e535", "#10B239FF"];
I'm not a fan of these new colors

2024-09-17 11:40 UTC, ztpn commented on src/components/player/atoms/settings/CaptionSettingsView.tsx
> +  const subtitleStore = useSubtitleStore();
I think there was a reason we didn't do this earlier and called the function every time

2024-09-17 11:40 UTC, ztpn commented on src/components/player/atoms/settings/CaptionSettingsView.tsx
> +            {/* Add Color Picker */}
Instead of using the default browser color picker we should use a lib like react-colorful or something

2024-09-17 11:40 UTC, ztpn commented on src/pages/parts/settings/CaptionsPart.tsx
> +              {/* Add Color Picker */}
It's better to make the color picker a component that can be used anywhere

2024-09-17 11:42 UTC, ztpn commented
Also the custom color button looks ugly 
It doesn't need to be bigger or have an outline
Should have some icon

2024-09-21 00:10 UTC, closed without merging